### ISSUE TITLE
<Ctlr-C> <Ctrl-D> kills roxterm

### ISSUE THREAD

**Issue by realh** [realh/roxterm#114]
As the title says, pressing <Ctrl-C> <Ctrl-D> closes roxtem no matter how many windows and/or tabs are open. This behaviour has been introduced in version 3.0.1. 

Reported by: *anonymous

Original Ticket: [roxterm/bugs/113](https://sourceforge.net/p/roxterm/bugs/113)

**Comment by realh** [comment]
Unable to reproduce.

**Comment by ramnes** [comment]
I tried yesterday and could not reproduce neither.
