### ISSUE TITLE
Does not set $VTE_VERSION

### ISSUE THREAD

**Issue by realh** [realh/roxterm#130]
VTE automatically sets the environment variable VTE_VERSION prior to spawning the child process. This works in all VTE-based emulators except roxterm. The intent is that applications (or e.g. shell startup scripts) can easily check whether the terminal is VTE-based, as well as whether it's new enough to support a certain feature.

Roxterm doesn't set and doesn't alter this value.

Is this in a bug in roxterm (e.g. it saves all the env vars at one point, and restores them later on)? I can see methods like roxterm_modify_environment(), is this relevant?

Or is this a bug in VTE that it does not always force setting this variable, and roxterm happens to trigger this bug?

Reported by: egmont

Original Ticket: [roxterm/bugs/129](https://sourceforge.net/p/roxterm/bugs/129)

**Comment by egmontkob** [comment]
Could it be that roxterm manually saves and restores the environment, like [gnome-terminal used to do](https://git.gnome.org/browse/gnome-terminal/commit/?id=e74c3e3fc)?

**Comment by realh** [comment]
It does, but I don't see why that would prevent vte from adding VTE_VERSION. Roxterm sets some variables of its own, so it has to pass an env into the spawn func anyway, so I don't understand what difference it makes whether it only passes its own variables or the whole of the parent env too.

Also,the parent process' env doesn't necessarily contain what the user would expect. If you do something like this from the command line or a script:

    roxterm --fork
    export FOO=bar
    roxterm --tab

The second roxterm command is forwarded to the first instance over dbus (later I'll use GtkApplication instead of interacting with dbus directly), so I forward the env vector too, otherwise the new tab wouldn't see the new value of FOO.

**Comment by realh** [comment]
It could be because gnome-terminal uses VTE_SPAWN_NO_PARENT_ENVV. Unfortunately that's undocumented, but looking through vte's source code, it appears I should use it.

**Comment by egmontkob** [comment]
Oh, I missed that you use **g**_spawn rather than **vte**_spawn... I guess you really should use the latter, that's what sets up this env var and probably does quite a few other things.

**Comment by egmontkob** [comment]
vte_xx_spawn_**sync** have been available for much longer, they became deprecated and replaced by vte_xx_spawn_**async** due to a design problem described in [bug 772354](https://bugzilla.gnome.org/show_bug.cgi?id=772354). Most VTE-based apps are yet to catch up.

(If I were you, I'd probably go for the newest, and require vte >= 0.48. Roxterm has been dropped at least by Debian and Ubuntu, probably others; by the time they'll resurrect the package and it'll reach users again by default, they'll sure have a new enough vte.)

**Comment by realh** [comment]
>>VTE_SPAWN_NO_PARENT_ENVV
>
>I have no idea what it does, but sure, give it a try :)

AFAICT it prevents vte from merging the env from the parent process with the one passed into the spawn functions.

> (If I were you, I'd probably go for the newest, and require vte >= 0.48. Roxterm has been dropped at least by Debian and Ubuntu, probably others; by the time they'll resurrect the package and it'll reach users again by default, they'll sure have a new enough vte.)

OK, that makes sense. I was a bit worried I might leave a gap for distros using vte < 0.48 and gtk >= 3.20, but it shouldn't be a problem.
