### ISSUE TITLE
Checks for obsolete VTE methods

### ISSUE THREAD

**Issue by egmontkob** [realh/roxterm#185]
`./mscript.py configure --disable-nls` says:
```
Checking for function vte_terminal_set_word_chars()... no
Checking for function vte_terminal_set_background_tint_color()... no
```

These two methods were present in libvte-2.90 or older, but never in libvte-2.91. As Roxterm only supports the latter, there's no point in looking for these methods.

**Comment by realh** [comment]
I'm changing the build system to meson, so various quirks and obsolete checks won't be carried over.
