### ISSUE TITLE
FYI: New APIs in VTE 0.52

### ISSUE THREAD

**Issue by egmontkob** [realh/roxterm#186]
FYI: VTE 0.52 (to be released in March) adds 3 new functionalities and their corresponding APIs. It's up to you whether you want to hook up and make config options for them.

- `vte_terminal_{get,set}_cell_{height,width}_scale`: Increased line spacing and character spacing mostly for accessibility for people with imperfect sight.

- `vte_terminal_{get,set}_bold_is_bright`: Whether escape sequences such as `\e[1;35m` switch to bright colors in addition to bold (legacy behavior) or switch to bold and leave the color intact (new behavior, required for solarized and similar modern color schemes). (And while at it, we've removed "Allow bold text" from `gnome-terminal`'s UI, and will probably start deprecating its API in about a year. I see no sane reason for this option to exist.)

- `vte_terminal_{get,set}_text_blink_mode`: VTE now implements blinking text (`\e[5m`) and enables it by default, this option lets you disable it or make it conditional to the terminal being (un)focused.

Please refer to VTE's source tree for details, e.g. compile with `--enable-gtk-doc` and check the generated docs under `doc/reference/html/index.html`.

**Comment by realh** [comment]
I've removed the "Allow bold" option, but I'll wait until the new VTE is released before supporting the new features, so that I can easily test them. Hopefully it'll get into Arch fairly quickly.

**Comment by egmontkob** [comment]
> I've removed the "Allow bold" option

Let me know if people complain, it's also an experimental step in gnome-terminal. We might change our minds if there's a good reason.

> Hopefully it'll get into Arch fairly quickly.

I think it's usually just a couple of days. Official VTE release is Mar 12-14.

**Comment by lolilolicon** [comment]
@egmontkob @realh
Please support bold text again. I like that by default bold is no more bright, but why "while at it" remove a perfectly valid feature? I use `di=01` in `$LS_COLORS` to display directories in bold and I've found it helpful.

**Comment by egmontkob** [comment]
The removal of "Allow bold" option means that it's always allowed now. `di=01` should result in bold text, which you can no longer disable in Roxterm.

**Comment by lolilolicon** [comment]
Oh, really? I thought bold text is no longer supported! After system update, my directories are no more in bold text.
So now I've tried with different fonts, and some (eg Noto Sans Mono Regular) did render a noticeable boldness, however others such as Monaco Regular do not seem to, not noticeably. It seems the font rendering has changed. A pity. I wonder if you know of a solution, eg fontconfig rules?

**Comment by egmontkob** [comment]
I can think of two things:

- VTE 0.54 no longer does "faux bold" when it used to print the same non-bold font twice, with a 1px horizontal offset, thus effectively boldening it.

- Bold font is only accepted if it's within a certain threshold from the original font's width, see https://gitlab.gnome.org/GNOME/vte/issues/97 (although this hasn't changed for 10 years).

It's probably the former. I'm not familiar with Monaco, but on http://fontsgeek.com/ I can see Monaco Regular but not Monaco Bold. So probably you used to have this "faux bold".

**Comment by lolilolicon** [comment]
Oh yeah must be. Thanks for your clarification! For me, rarely any font looks good in the terminal at a not-too-large size. The faux bold did well for me though, I'd like it back... Would it be possible for you to point me to the commits that I might use to create a revert patch? Thanks!

**Comment by egmontkob** [comment]
In VTE's repository you can easily find the commit whose log message contains "faux bold". There were subsequent changes though on top of this, I'm not sure how easy it is to revert it.

**Comment by lolilolicon** [comment]
OK, thank you very much. I might try...

**Comment by lolilolicon** [comment]
I got "faux bold" back simply by reverting f0ee057. Thank you!
