### ISSUE TITLE
Transparent tab bar with Ambiance

### ISSUE THREAD

**Issue by egmontkob** [realh/roxterm#187]
Ubuntu Artful, using its default Ambiance theme.

The tab bar, except for the active tab (that is: inactive tabs [or all tabs if the window is unfocused], unused area, and the + button) are transparent.

![roxterm-transparent](https://user-images.githubusercontent.com/5750745/36447564-0577d118-1685-11e8-92cc-1f0d98a4d516.jpg)

**Comment by egmontkob** [comment]
Non-overlay scrollbar is also transparent on Ambiance.

**Comment by realh** [comment]
I've tested this with an AUR port of Ubuntu themes and it seems OK now.

**Comment by egmontkob** [comment]
Yup, okay for me too. Thanks!
