### ISSUE TITLE
Misleading padding in entry boxes

### ISSUE THREAD

**Issue by egmontkob** [realh/roxterm#188]
In the profile editor, all the entry boxes have a misleading (and IMO ugly) extra padding. See the screenshot where the value "%s" looks as if it was " %s" with maybe 1 or 2 leading spaces.

Other dialogs, such as Find or Set Window Title don't have this.

Apparently it's caused by the fields related to {primary,secondary}_icon in the glade file. Even though there's no actual icon specified, the presence of any such field in the xml causes an empty image to be shown along with its padding.

This is also confirmed by GTK+ Inspector. If you inspect the entry box and switch to "CSS nodes", you'll see two children of name "image" with a side padding of 5px, these nodes don't appear if you remove the aforementioned lines from the xml.

![roxterm-entry-padding](https://user-images.githubusercontent.com/5750745/36471716-c8586fd4-16ef-11e8-9d32-fd1a7bd344bd.png)

**Comment by realh** [comment]
Glade doesn't seem to offer any control over whether those fields are added, but it shows a blue underline in the spaces you've highlighted. For me (using Adwaita) the Colour scheme has this padding as well. I've tried mass-deleting those properties and it didn't seem to make any difference. I don't think I can do anything about this, perhaps it's a bug in GTK, glade or Ambiance?

**Comment by egmontkob** [comment]
I've experienced the same problem both with Adwaita and Ambiance. On Adwaita it's essentially the same for me, the same misindentation between "%s" and "(Don't set)".

I didn't use Glade to edit those files, rather just manually removed the relevant lines. (Toggling True vs False didn't make any difference.) Removing these lines removed the extra padding for me. Could you please double check this again?

The behavior could, of course, depend on the exact GTK+ version or whatnot. (I'm on Ubuntu Artful.)

I _guess_ glade is clever enough not to add back these entries once you've removed them, assuming you don't tamper with relevant settings on the UI. I'd guess so because I don't recall seeing such huge padding anywhere else, that's why it looked so weird to me in Roxterm. This could also depend on the Glade version or lunar phase or whatever else.

**Comment by egmontkob** [comment]
What you could also do (also with the "Colour scheme" combobox, I'm curious what you see there) is how I debugged this with GTK+ Inspector: Start

    GTK_DEBUG=interactive roxterm-config --EditProfile=Default

Click on the "shooting target" button in the Inspector's header bar (tooltip: Select an Object), then on the entry box or combo box in Roxterm's profile editor. Change the Inspector's dropdown from "Miscellaneous" to "CSS nodes".

In the left hand treeview, an "entry" is highlighted. In the correct (no extra padding) case it has two "undershoot" children. In the incorrect (extra padding) case it has two more "image" children, at least for me.

Fun: These "image" children have a 5px _padding_ in Ambiance, but a 6px _margin_ in Adwaita.

**Comment by realh** [comment]
At some point I've committed a version of the .ui file with the properties removed, and I don't see those image children in the debugger, so hopefully it's OK now?

**Comment by egmontkob** [comment]
OK for me, thanks! Is it okay for you too? :)
