### ISSUE TITLE
Blur background

### ISSUE THREAD

**Issue by ramnes** [realh/roxterm#190]
It would be fancy to have a blur option, just like the transparency one.

The goal would be to achieve something like this:

![blur example](https://i.redditmedia.com/MZwCB_9zUfQVhqXEAbOlaMI32Kf3_1kZlcJ4jlt27YQ.jpg?w=1024&s=9b617ae8b462084ccbfd0eb3d0931076)

[(source)](https://www.reddit.com/r/unixporn/comments/7ycvar/macos_minimalist_blur/)

**Comment by realh** [comment]
That's really nice, but I don't think GTK supports anything like that directly. To implement it smoothly I would have to interact with the compositor I guess, and I don't know how to do that.

**Comment by ramnes** [comment]
Looks like it has been done for GTK4: https://wiki.gnome.org/Projects/GTK%2B/Roadmap/GTK4

And apparently rxvt-unicode has a built-in blur option, but I can't get it to work.

**Comment by ramnes** [comment]
I've managed to make it working with compton, but it's terribly bad on performances, even with their OpenGL backend.

![compton](https://i.imgur.com/DezZHPo.png)

This is the result of `compton -cG -r10 -o.1 --backend glx --glx-no-stencil --glx-no-rebind-pixmap --glx-swap-method buffer-age --blur-background --blur-kern '15,15,0.140858,0.182684,0.227638,0.272532,0.313486,0.346456,0.367879,0.375311,0.367879,0.346456,0.313486,0.272532,0.227638,0.182684,0.140858,0.182684,0.236928,0.295230,0.353455,0.406570,0.449329,0.477114,0.486752,0.477114,0.449329,0.406570,0.353455,0.295230,0.236928,0.182684,0.227638,0.295230,0.367879,0.440432,0.506617,0.559898,0.594521,0.606531,0.594521,0.559898,0.506617,0.440432,0.367879,0.295230,0.227638,0.272532,0.353455,0.440432,0.527292,0.606531,0.670320,0.711770,0.726149,0.711770,0.670320,0.606531,0.527292,0.440432,0.353455,0.272532,0.313486,0.406570,0.506617,0.606531,0.697676,0.771052,0.818731,0.835270,0.818731,0.771052,0.697676,0.606531,0.506617,0.406570,0.313486,0.346456,0.449329,0.559898,0.670320,0.771052,0.852144,0.904837,0.923116,0.904837,0.852144,0.771052,0.670320,0.559898,0.449329,0.346456,0.367879,0.477114,0.594521,0.711770,0.818731,0.904837,0.960789,0.980199,0.960789,0.904837,0.818731,0.711770,0.594521,0.477114,0.367879,0.375311,0.486752,0.606531,0.726149,0.835270,0.923116,0.980199,0.980199,0.923116,0.835270,0.726149,0.606531,0.486752,0.375311,0.367879,0.477114,0.594521,0.711770,0.818731,0.904837,0.960789,0.980199,0.960789,0.904837,0.818731,0.711770,0.594521,0.477114,0.367879,0.346456,0.449329,0.559898,0.670320,0.771052,0.852144,0.904837,0.923116,0.904837,0.852144,0.771052,0.670320,0.559898,0.449329,0.346456,0.313486,0.406570,0.506617,0.606531,0.697676,0.771052,0.818731,0.835270,0.818731,0.771052,0.697676,0.606531,0.506617,0.406570,0.313486,0.272532,0.353455,0.440432,0.527292,0.606531,0.670320,0.711770,0.726149,0.711770,0.670320,0.606531,0.527292,0.440432,0.353455,0.272532,0.227638,0.295230,0.367879,0.440432,0.506617,0.559898,0.594521,0.606531,0.594521,0.559898,0.506617,0.440432,0.367879,0.295230,0.227638,0.182684,0.236928,0.295230,0.353455,0.406570,0.449329,0.477114,0.486752,0.477114,0.449329,0.406570,0.353455,0.295230,0.236928,0.182684,0.140858,0.182684,0.227638,0.272532,0.313486,0.346456,0.367879,0.375311,0.367879,0.346456,0.313486,0.272532,0.227638,0.182684,0.140858'`

Let's close this for now, I'll reopen it when GTK4 is out.

**Comment by realh** [comment]
GNOME 40 supports this, and it can be enabled with the blur-my-shell extension, but it's still rather experimental I think, with lots of issues. Anyway, this is really a GNOME feature, not something that roxterm can control, so I'll leave this issue closed.
