### ISSUE TITLE
Bad substitution

### ISSUE THREAD

**Issue by egmontkob** [realh/roxterm#192]
Current git:

    $ cd build
    $ cmake ..
    /home/egmont/src/roxterm/version.sh: 5: /home/egmont/src/roxterm/version.sh: Bad substitution

On Ubuntu, `/bin/sh` is a symlink to `dash`. This script should explicitly call `#!/bin/bash` as it contains bash-ism.

**Comment by realh** [comment]
Which do you think is a more portable solution, using bash or sh and sed?

**Comment by egmontkob** [comment]
Dunno, I'd say up to you. Maybe `#!/usr/bin/env bash` is somewhat more portable than `#!/bin/bash`, since on some rare systems it's `/usr/local/bin/bash`. `/bin/sh` and `sed` should also be absolutely fine.
