### ISSUE TITLE
Regex matches don't work

### ISSUE THREAD

**Issue by egmontkob** [realh/roxterm#194]
URLs should be automatically recognized, shouldn't they? I can see relevant code. However, it doesn't work for me, mouseover does nothing special.

At this moment I have no clue why it doesn't work, and whether it's roxterm's or vte's fault. Works in other vte-based emulators, though.

Does it work for you? :)

**Comment by egmontkob** [comment]
Changing from `#define ROXTERM_REGEX_FLAGS (VTE_REGEX_FLAGS_DEFAULT | PCRE2_MULTILINE | PCRE2_NEWLINE_CRLF)` to `#define ROXTERM_REGEX_FLAGS 0` makes regexes work.

---

Including `PCRE2_NEWLINE_CRLF` in this flag is a semantical bug, this is not a flag but an enum-ish value that happens to be 3, hence it ends up actually being `0x00000001 | 0x00000002` aka. `PCRE2_ALLOW_EMPTY_CLASS | PCRE2_ALT_BSUX`, whatever these mean.

It looks to me that `PCRE2_NEWLINE_CRLF` is meant to be used via the `ccontext` parameter of `pcre2_compile()` rather than the `options` parameter. Not sure, I'm just reading pcre2's docs with no experience. VTE probably doesn't expose this option and you shouldn't need it.

However, removing this value from the flag doesn't fix the actual issue, so it's not the bug we're hunting here.

---

`ROXTERM_REGEX_FLAGS` is used twice: first in a call to `vte_regex_new_for_match()` where this denotes regex _compile_ options, and then to `vte_terminal_match_add_regex` where this is _match_ options. Even though these flags are in the same space (see the C J M D comments in `pcre2.h`) and even though the currently irrelevant `pcre2_jit_match()` document that "[u]nsupported options are ignored", I can't see this sentence in the docs of `pcre2_compile` or `pcre2_match`. The existence of the error code `PCRE2_ERROR_BADOPTION` implicitly suggests that it's indeed not the case, it seems to me that the caller is responsible for passing compile options only to the compile method, and match options only to the match method.

Which in turn raises the issue that `VTE_REGEX_FLAGS_DEFAULT` should be `VTE_REGEX_COMPILE_FLAGS_DEFAULT` and/or `VTE_REGEX_MATCH_FLAGS_DEFAULT` instead. Moreover, I'm wondering why we have such a variable publicly visible. What's the point if it's not used in `gnome-terminal`, and `roxterm` also works fine if using `0` instead?? Dunno.

**Comment by realh** [comment]
I just didn't read the docs properly and realise the difference between compile flags and match flags. I still don't know how I'm supposed to use that CRLF constant, or remember why the old flags needed a CRLF, so I've left that out.
