### ISSUE TITLE
Regex problem with parentheses

### ISSUE THREAD

**Issue by realh** [realh/roxterm#195]
Roxterm's own README.md shows an example of the problem when viewed as text source in roxterm. It incorrectly includes the `)` as part of the first URL. Parentheses are valid in URLs, and commonly used by Wikipedia, so simply excluding them would also be incorrect. It might be possible to do something clever with pcre2, but I'm not looking forward to working out how.

The reason the second URL is matched correctly is because it's a different pattern or sub-pattern, without a filename component.

**Comment by egmontkob** [comment]
See [g-t 763980](https://bugzilla.gnome.org/show_bug.cgi?id=763980) on top of an earlier giant regex rewrite. Also [g-t 448044](https://bugzilla.gnome.org/show_bug.cgi?id=448044) for the same with apostrophes, which surprisingly required a quite different technical approach.

**Comment by realh** [comment]
I was surprised to see how clever g-t is with them and almost awestruck by your terminal-regex.h. I think the best thing for me to do is copy them into roxterm without trying to change them, and probably simplify the launching by just passing everything through xdg-open, except for ssh.
