### ISSUE TITLE
Role option removed

### ISSUE THREAD

**Issue by hicolour** [realh/roxterm#196]
Is there any reason why `role` parameter was removed. It was very usefull especially in case of tailling windows mangment systems.

```
       --role=ROLE
           Sets the X window system "role" hint for the window being created.
```

**Comment by realh** [comment]
The documentation for `gtk_window_set_role` says it's only useful in X11, and I wanted to avoid anything X-specific in case it compromised Wayland. But role is probably safely ignored on other platforms so perhaps I'll bring it back.

**Comment by hicolour** [comment]
Please do, it's very handy when you have multiple terminal applications and you want manage their lifecycle eg. by having scratchpads. 
many thanks
