### ISSUE TITLE
roxterm ppa is signed with rsa1024 key, needs to be 2048 bits or more

### ISSUE THREAD

**Issue by crgithubmoth** [realh/roxterm#200]
IIRC all browsers now warn about rsa cert keys <=1024 bits
Apt does not, but that is another bug
Please add a stronger key to the ppa sig

**Comment by realh** [comment]
The key I usually use now is 4096 bits, and that's what my packages are signed with, but I can't work out how to add it to the PPA.

**Comment by crgithubmoth** [comment]
Not possible AFAICT, 
Several bugs on launchpad,
https://bugs.launchpad.net/launchpad/+bug/1331914
Thanks for trying

**Comment by crgithubmoth** [comment]
gpgv shows noble ppa signed by Tony Houghton 4096 bits and the old realh key, closing
