### ISSUE TITLE
Window title "Unnamed Window"

### ISSUE THREAD

**Issue by jfcolom** [realh/roxterm#202]
Roxterm 3.7.3 seems not to honor the '%s' especial template symbol for window title any more. If title is set to %s, the window shows "Unnamed Window"

**Comment by realh** [comment]
I can't reproduce that. "Unnamed Window" doesn't appear anywhere in roxterm's code, it's probably what GTK uses if you don't call gtk_window_set_title() at all. Possibly a library update could have broken something, can you try recompiling roxterm?

**Comment by jfcolom** [comment]
I updated roxterm from my binary distribution. By diving a little bit into the source code I guess the problem may have to do with the behavior of `vte_terminal_get_window_title()` from vte3 library. In fact, vte3 package has been updated from 0.52 to 0.54 at the same time.

As a workaround, I have set this variable in my `.bashrc`
`PROMPT_COMMAND='echo -en "\033]0;$(whoami)@$(hostname):$(pwd)\a"'`
