### ISSUE TITLE
Incorrect linker flags (was crash when dragging tabs)

### ISSUE THREAD

**Issue by yujiri8** [realh/roxterm#203]
I'm on FreeBSD (12.0-STABLE release) and using DWM (version 6.1_3) as my window manager. This happens consistently.

**Comment by aprogrammer8** [comment]
Update: I just tried it out on Xfce, version 4.12. The same thing happens.

**Comment by realh** [comment]
That sounds vaguely familiar, what version of roxterm are you using? Can you get a backtrace that identifies the lines in the source code where the problem occurred?

**Comment by aprogrammer8** [comment]
Sorry, somehow I included the versions of FreeBSD and both window managers but forgot to include the roxterm verison :/ I seem to have version 3.3.2_1 installed.

Not sure about the backtrace. I did get this error though when reproducing the problem by using another terminal to start roxterm so I could see the output:

`** (roxterm:29356): WARNING **: 21:49:01.089: Failed to connect to session manager: SESSION_MANAGER environment variable not defined`

**Comment by aprogrammer8** [comment]
Ah, apparently that's an old version. It's the latest FreeBSD has in its package repo. I should try compiling from source or something to get the latest version.

**Comment by realh** [comment]
Yes, it's difficult for me to support such an old version. However, it sounds like you might also have an old version of gtk3 (< 3.20), otherwise you would probably also have run into the notorious shrinking window bug. If so, that would also imply an old version of vte, which might not be compatible with the latest version of roxterm. I dropped support for some legacy APIs to help keep my code cleaner, thinking that people stuck with older libraries could just stick to roxterm 3.3 without problems :-(.

Please let me know whether you're successful with the latest version of roxterm, and what versions of gtk3 and vte you have.

The SESSION_MANAGER warning is harmless, it's just trying to use session management, which was a feature of older desktops, but now seems to be obsolete. That's something else I removed later on (sort of - I reused most of the code to add manual roxterm session management), but  older versions can just carry on without SM anyway.

**Comment by yujiri8** [comment]
Sorry I disappeared for so long. I'm trying to get back to this now but I can't for the life of me get roxterm to build. With source for version 3.7.5 checked out, the INSTALL file says:
```
ROXTerm now uses CMake to build and install.

Requirements
************

ROXTerm additionally needs xsltproc (and docbook-xsl if building without net
access), and everything else required to compile an application linked with
vte.

Building with CMake
*******************

Using a separate build directory is recommended:

mkdir build
cd build

To see available build options etc:

cmake --help ..

To configure make:

cmake .. [OPTIONS]

Build step:

make -j 4

(the -j 4 is optional, but recommended for quad core CPUs).

Install:

sudo make install
```

`cmake ..` appears to work but gives me a couple of warnings:
```
WARNING: Target "roxterm-config" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "roxterm-config" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "roxterm" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "roxterm" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
```
Then make fails with:
```
/usr/bin/ld: error: unable to find library -lgtk-3
/usr/bin/ld: error: unable to find library -lgdk-3
/usr/bin/ld: error: unable to find library -lpangocairo-1.0
/usr/bin/ld: error: unable to find library -lpango-1.0
/usr/bin/ld: error: unable to find library -latk-1.0
/usr/bin/ld: error: unable to find library -lcairo-gobject
/usr/bin/ld: error: unable to find library -lcairo
/usr/bin/ld: error: unable to find library -lgdk_pixbuf-2.0
/usr/bin/ld: error: unable to find library -lgio-2.0
/usr/bin/ld: error: unable to find library -ldbus-glib-1
/usr/bin/ld: error: unable to find library -ldbus-1
/usr/bin/ld: error: unable to find library -lgobject-2.0
/usr/bin/ld: error: unable to find library -lglib-2.0
/usr/bin/ld: error: unable to find library -lintl
/usr/bin/ld: error: unable to find library -lgmodule-2.0
/usr/bin/ld: error: unable to find library -lglib-2.0
/usr/bin/ld: error: unable to find library -lintl
/usr/bin/ld: error: unable to find library -lgmodule-2.0
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /root/code/roxterm/build
*** Error code 1

Stop.
make[1]: stopped in /root/code/roxterm/build
*** Error code 1

Stop.
make: stopped in /root/code/roxterm/build
```

I did some digging and found that other people (with other CMake-based projects) solved similar errors by passing flags to cmake to tell it where to find the libraries, but the names of the flags don't seem to be predictable. I tried -DGMODULE_LIBRARY and -DGMODULE_LIB; both said "Manually specified variables were not used by the project:..." and still threw the error for gmodule.

By the way, I have GTK3 version 3.24.10 and VTE 3 version 0.52.2 (VTE 1 is a separate package which I have 0.28.2 of).

Does this build process work without special stuff for you? Is it possible it's a Linux vs BSD thing?

**Comment by realh** [comment]
I haven't had that problem. From the first set of warnings from cmake it looks as if the flag for adding a library directory is getting mixed up with the flag for adding a library file. I use cmake's pkg-config module to get these flags; I might have been using it in an incorrect way that I could get away with on Linux (or older version of cmake) but breaks elsewhere, so I'll check that when I have time.

**Comment by realh** [comment]
I think I've found my mistake and fixed it. Please can you pull latest from git and try again?

**Comment by yujiri8** [comment]
That was it! I got it built and dragged the tab without it crashing.

Great job! I'm switching back to roxterm :)

**Comment by realh** [comment]
Thanks.
