### ISSUE TITLE
Ansi blink squence ingored.

### ISSUE THREAD

**Issue by tsjnachos117** [realh/roxterm#207]
If I type `printf '\e[5m123\e[m\n'` into BASH, I should get a line with a blinking "123". Instead, I get a non-blinking "123". It seems this particular ANSI sequence is outright ignored.

I'm running Ubuntu 18.04 (x64), and I just tested this with a new build (Help > About says I'm running version 3.7.3) from the latest git.

**Comment by BackSeat** [comment]
I just tried this and it works for me (Debian Buster, ROXTerm 3.3.1.15~gca5efda).

**Comment by tsjnachos117** [comment]
@BackSeat Since your version is older, perhaps my bug is a regression. Or, maybe you just have a newer/better libvte than me? (Buster is newer than Ubuntu 18.04, so out probably would have a newer lib.)

**Comment by tsjnachos117** [comment]
Ok, I'm guessing this is a regression, since this bug is also affecting my own Debian Buster rig. It too is running Roxterm 3.7.3.

**Comment by egmontkob** [comment]
In order to have blinking text, you need these two:

- VTE (Debian/Ubuntu package name: libvte-2.91-0) version 0.52 or newer. Ubuntu 18.04 and Debian Buster should be okay.

- If using ROXTerm 3.6.1 or newer, the corresponding configuration option has to be enabled under Preferences -> Edit Current Profile.

**Comment by tsjnachos117** [comment]
@egmontkob

>If using ROXTerm 3.6.1 or newer, the corresponding configuration option has to be enabled under Preferences -> Edit Current Profile.

I did not know that. I guess this isn't a bug, after all, as I can confirm that changing this setting works on my Debian system. (I haven't checked Ubuntu yet, but honestly, do I really need to?) Sorry for wasting everyone's time. I'm just going to go ahead and close this now.
