### ISSUE TITLE
Tab label widget CSS selectors don't work

### ISSUE THREAD

**Issue by vossenjp** [realh/roxterm#214]
I recently upgraded from Mint-18.3 (ROXTERM 3.3.2-1) to Mint-19.3 (roxterm-3.7.3-1ppa1bionic1) and now my tab labels are too big to fit.  I want 17 tabs open with a geometry of 110 columns and I need both numbers and close buttons (because I need the "terminal status in close button"--thanks for that way back when!).  I've named many of the tabs, and all of that used to fix well enough that would could see the number, "enough" of the name, and the close button.

With this latest ROXTerm all I get is "...".  I have to drop to 14 tabs and raise to 124 columns before I get a similar effect to my previous install.  I might be able to live with 124, but losing 3 tabs is a bit of a pain because I do different things in all of them.

I suspect this has more to do with new/different default GTK fonts (Ubuntu fonts in bionic?) than ROXTerm itself, but it would be awesome if ROXTerm could provide a way to override & tweak tab label fonts & size.  Failing that, some docs about what fonts are used and where to change them would be great.  I've spent some time googling for that info and I've failed to find it if it's out there.  An override would be really nice because I like the current default font and size pretty much everywhere BUT in the ROXTerm tab labels.

Tony, thanks as always for the awesome tool and the PPA to make it easy to keep up with!  I've gotten a lot of folks at $WORK hooked on ROXTerm as well, as we spent much of our days in terms/ssh.

**Comment by realh** [comment]
I don't remember whether I changed the way the tabs are labelled since 3.3. You can change the font size by adding this to `~/.config/gtk-3.0/gtk.css`:

    notebook tab label { 
      font-size: smaller;
    }                       

It should be possible to make it specific to roxterm's labels by replacing `notebook tab` with `multitab-label`, but that doesn't seem to work for some reason. Hopefully you won't mind this affecting other programs.

[The GTK manual](https://developer.gnome.org/gtk3/stable/chap-css-properties.html) lists what properties you can change in case you want to fine tune the size.

**Comment by vossenjp** [comment]
**Summary**: that worked but it's not clear how much it will really help because I have to test on another node with different resolution.  Is the padding around the label and the close button also tweakable?

**Details**:
Interesting.  First, I found that GTK manual hopeless, which I think is partly because CSS confuses the heck out of me and partly because it assumes I know way more about a lot of GTK & CSS things than I do.

For testing it seems like I have to log out and back in for the change to take effect.  Is there any other way to kick GTK to make the change effective without log-out/in?  I have a large amount of state in my 1920x(1080|985) nodes, so logging out or rebooting is quite painful.  I can easily test elsewhere, but that screen is 1440x900 so testing ROXTerm & tabs is not apples-to-apples.

I created `~/.config/gtk-3.0/gtk.css` (the dir was there but the file wasn't), and I confirm that `notebook tab label` affects at least ROXTerm and Geany but `multitab-label label` (is that right?) does not.  Neither setting seemed to affect Firefox, but those are all I've tested so far.  Again, this is all Mint-19.3 XFCE.

Testing on just the 1440x900 screen with RT at 110 cols of _monospace regular 12_ gives the following tab count for the label to be nothing but "... x" and "NN... x" respectively (where "x" is the close button):

| Setting  | ... x | nn... x |
| -------- | ----- | ------- |
| xx-small | 19    | 15 |
| x-small  | 18    | 14 |
| small    | 17    | 13 |
| No file  | 17    | 13 |

**Comment by realh** [comment]
You should be able to use other values for `font-size`, eg `90%`, `10px`, `10pt` etc if `smaller` isn't quite doing what you want.

When I tested it I didn't have to log out to apply the changes in gtk.css to roxterm, but you probably need to restart roxterm ie close all terminals and/or use "Quit" from the app menu if your desktop supports that.

I think I've worked out why `multitab-label` doesn't work as a selector; I made a mistake in the code, so I'll need to make a new release to fix that bug.

I'm not sure what you can do about the padding, but [GtkInspector](https://wiki.gnome.org/action/show/Projects/GTK/Inspector) might help you to work it out.

**Comment by realh** [comment]
I've fixed the CSS selectors now. The top-level tab label is a `multitab-label`. It contains a box containing a vanilla `label` and a `multitab-close-button`.

**Comment by vossenjp** [comment]
Huh, on my Mint-19.3 XFCE the new GTK settings do not take effect until I log out and back in.  I wonder if that's maybe an XFCE thing?

Awesome news about the bug-fix!  I see that will be in "3.8.3-1ppa1eoan1", any chance of getting it in bionic too?  I've got roxterm-3.7.3-1ppa1bionic1 right now, and I've updated and checked and that's the latest.

Also, what does the CSS look like for the new labels?  And does anything else use them, or only ROXTerm?

Thanks again!

**Comment by realh** [comment]
Oops, that reminds me I forgot to upload it to the PPA; I've switched to Arch on my own PCs and I don't automatically remember to build debs any more. I've done it now.

IIRC I deliberately released the last few versions for disco instead of bionic because there were some important changes in vte. I don't know what Mint 19.3 is based on, but you will probably be able to at least build 3.8.3 from the source deb.

In the new version you can use `multitab-label label` as a selector instead of `notebook tab label`, but the latter will still work too. Nothing except roxterm uses 'multitab-label' AFAIK.

**Comment by vossenjp** [comment]
Mint-19 is based on Bionic (thus using `roxterm-3.7.3-1ppa1bionic1`). :-)  Any chance of back-porting the code fix to Bionic, even if the new vte stuff's not there?

And the CSS should look like this then?
```
/* Tweak ROXTerm (3.8.3+) tabs per https://github.com/realh/roxterm/issues/214 */
multitab-label label {
  font-size: x-small;
}
multitab-close-button label {
  font-size: x-small;
}
```

I was talking about this at $WORK today and as we looked at it, it seems like there might be more space between the edge of the label and the label itself, bad ASCII art as follows.  Not sure if that's adjuastable either?
```
     ------------
Old: | 1. Tab X |

     --------------
New: |  1. Tab X  |

```

**Comment by realh** [comment]
If you don't mind the changes possibly affecting other programs you don't really need the bug fix, which only sets the names to make it easier to select them in CSS. MultitabLabel is derived from GtkEventBox so you could use `notebook tab event-box` (I think) as a selector. It contains a GtkLabel and a MultitabCloseButton (derived from GtkButton) so you should be able to use `notebook tab event-box label` and `notebook tab event-box button`. The `event-box` is kind of redundant, but may help if you don't want to affect other apps too, and/or may have margins and padding you can change. Changing the font size of the button probably won't help, but all of these widgets may have padding and/or margins you could change. I don't know exactly what those properties would be, but I think you could probably find them out with GtkInspector.

**Comment by vossenjp** [comment]
One mystery solved, I think: it looks like if you start a new ROXTerm window with an existing one open, new GTK settings are not picked up.  But if no ROXTerm is running, then new GTK settings are picked up without a log out.  My problem is, ROXTerm is the first window I open and it's always open...

The "generic" GTK fix that affects other things (like Geany) has worked well enough for now, and work/life got really busy.  I will work on this more when I have a moment, but meanwhile thank you for all the help or for the great tool.

**Comment by BMJ-pdx** [comment]
> One mystery solved, I think: it looks like if you start a new ROXTerm window with an existing one open, new GTK settings are not picked up. ...

A little late on this, but:
If you invoke roxrerm with '--separate', (separate process), you should get a fresh start, i.e. new settings.
Probably a good idea for any testing.
