### ISSUE TITLE
Successful build on Ubuntu 19.10

### ISSUE THREAD

**Issue by mattcollier** [realh/roxterm#215]
```
sudo apt install cmake gtk+-3.0 libdbus-glib-1-dev vte-2.91 xsltproc
```
and then follow instruction in INSTALL

To maintainers, is there a place to document these OS deps?

Thanks!!

**Comment by realh** [comment]
The git repository includes a debian directory, so the dependencies can be checked by looking in `debian/control`. You can also take advantage of that directory to build a package on a modern Debian-based distro, or just install it from the [PPA](https://launchpad.net/~h-realh/+archive/ubuntu/roxterm) if you're using Ubuntu 19.10.

**Comment by mattcollier** [comment]
Thanks for the info.  Closing.
