### ISSUE TITLE
Compilation fails as some kernels < 5.0 have two-version of access_ok()

### ISSUE THREAD

**Issue by turnstep** [realh/roxterm#218]
Trying on CentOS 8.1 from git HEAD as of 2e7c099370756e6225166fdb3f203ae04b53fc7e. Failed to compile as the check around line 665 of os_dep/linux/rtw_android.c fails:

```
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5,0,0))
        if (!access_ok(priv_cmd.buf, priv_cmd.total_len)) {
#else
        if (!access_ok(VERIFY_READ, priv_cmd.buf, priv_cmd.total_len)) {
#endif
```

It tries to run the 3-arg version, but my kernel has the 2-arg version, despite being less than 5.0.0. Can see the 2-version defined  here:

/usr/src/kernels/4.18.0-147.5.1.el8_1.x86_64/arch/x86/include/asm/uaccess.h

Reducing the kernel version in the test allows it to proceed, but I suspect a better solution may be to somehow test which version is available, regardless of the version (or, run such a test if kernel is < 5, as I think we can safely say that >= 5 has the 2-arg, but < 5 *might* have the 2-arg)

**Comment by realh** [comment]
I think you've got the wrong project. That isn't part of roxterm's code, the filename seems to be part of a realtek wifi driver.

**Comment by turnstep** [comment]
Heh, #ETOOMANYTABS, sorry about that.
