### ISSUE TITLE
How to create a Default file of keyboard shortcut

### ISSUE THREAD

**Issue by abdulbadii** [realh/roxterm#227]
This annoying prompt keep on popping up at Roxterm startup:

` Unable to read keys from shortcuts file Shortcuts/Default: unknown reason
`

So how the guideline in creating a Default file of keyboard shortcut ? Thanks before.

**Comment by realh** [comment]
Strange. "Unknown reason" is one of those things that should never happen, but a programmer has to check for to be really thorough. If you installed roxterm in the default location (I think it's `/usr/local` but it could be `/usr`) the file should be in `/usr/local/share/roxterm/Config/Shortcuts/Default`. If it's missing or something copy the one from `Config/Shortcuts/Default` to `~/.config/roxterm.sourceforge.net/Shortcuts/Default`.

**Comment by abdulbadii** [comment]
Corrrect, gets fixed after the copy
I think we need to improved CMakeLists.txt to yield makefile with `install `target doing such copy..

**Comment by realh** [comment]
That's already supposed to happen:

```
install(DIRECTORY Config
    DESTINATION ${CMAKE_INSTALL_DATADIR}/roxterm)
```

but for some reason it went wrong for you. Have you checked `/usr/local/share/roxterm`?
