### ISSUE TITLE
nano editor, select text with shift+(down/up) not working

### ISSUE THREAD

**Issue by bokunodev** [realh/roxterm#230]
for some reason, i cannot select text using `shift + up/down` in nano editor.
`shift + left/right` works just fine.
also, `mononoki` font did apear is fonts list.

**Comment by realh** [comment]
The default keyboard shortcuts config uses those keys to scroll the terminal. You can edit the Shortcuts and remove the lines for <Shift>Up and <Shift>Down. I should probably remove those from the Default file too.

Do you mean you've installed a font called mononoki and it doesn't appear in roxterm's list? Please also check gnome-terminal to  test whether it's a roxterm bug or something else.

**Comment by bokunodev** [comment]
yes, i installed mononoki and its did apear in the list.
if i set `font` options in `$HOME/.config/roxterm.sourceforge.net/Profiles/Default` manually to `mononoki 10`, its works.
-
btw i use roxterm-git from aur

**Comment by realh** [comment]
I must have decided to prevent the default from being overwritten. You can either copy it first and make the new copy your default by clicking its radio in that box, or you can edit `/usr/share/roxterm/Config/Shortcuts/Default` as root.

The Mononoki font doesn't show up in gnome-terminal either, but it does in gedit. Both terminal apps have a filter to hide non-monospace fonts, according to `pango_font_family_is_monospace()`, but gedit does allow non-monospace. Maybe they neglected to set a flag in the font?

**Comment by bokunodev** [comment]
Thanks, i copied `Shortcut/Default` from `/ush/share` to `~/.config` and change
`<Shift>(Up/Down)` to `<Shift><Control>(Up/Down)` and it solve the problem. :)
