### ISSUE TITLE
Font selector filters fonts / some invisible

### ISSUE THREAD

**Issue by flohoff** [realh/roxterm#232]
Hi,
i am typically using "Roboto Mono for Powerline Regular" installed in my home directory from the github repo at:

https://github.com/powerline

Interestingly it will NOT show up in roxterm using Debian/Bullseye. I can select it in libreoffice and the default cinnamon/gnome font choose, roxterm will not offer it to me.

When editing the config file i can put the Fonts name in it:

flo@p5:~$ grep -i font ~/.config/roxterm.sourceforge.net/Profiles/Default 
font=Roboto Mono for Powerline Regular 10

And this works.

Flo

**Comment by realh** [comment]
Does it work in gnome-terminal? That and roxterm use filters in the selector dialogs so they only show monospace fonts. It looks like some fonts don't set the monospace flag that the filter looks for. Someone else reported a similar problem a few months ago, but I can't remember which font. I wonder if there's something you can do with fontconfig to override the flag.

**Comment by flohoff** [comment]
Gnome terminal has the same problem. Font not listed. Interesting.

**Comment by flohoff** [comment]
Still the case with Debian/Bookworm, current ROXTerm git. Still the case with Gnome Terminal 

`ii  gnome-terminal 3.46.8-1     amd64        GNOME terminal emulator application`

**Comment by flohoff** [comment]
Its not a problem in ROX Terminal. Loading the font into FontForge and saving it again makes it selectable. So the font itself seems to be damaged and misses some monospaced hints.

Sorry for the noise and thanks for ROXTerm ... I owe you more than one Beer ...

Flo
