### ISSUE TITLE
Potential Bug: Scrolling settings behavior change

### ISSUE THREAD

**Issue by davama** [realh/roxterm#234]
Recently updated to `roxterm-git 1:3.10.1.r2.gc708bf4-1` 

After the update, I was no longer able to scroll with my mouse scroll-wheel.
Had to make changes to my Default profile to finally make it work again.
See below:

Before the update:
```
[roxterm profile]
colour_scheme=Nocturne
background_type=2
saturation=0.209890
font=Monospace 10
audible_bell=0
hide_mouse=0
bell_highlights_tab=1
cursor_shape=0
term=xterm
browser=google-chrome-stable
scrollbar_pos=0
scrollback_lines=100000
scroll_on_output=0
scroll_on_keystroke=1
always_show_tabs=0
show_add_tab_btn=0
hide_menubar=1
win_title=%s
login_shell=0
```

After the update:
```
[roxterm profile]
colour_scheme=Nocturne
background_type=2
saturation=0.209890
font=Monospace 10
audible_bell=0
hide_mouse=0
bell_highlights_tab=1
cursor_shape=0
term=xterm
browser=google-chrome-stable
scrollbar_pos=1
scrollback_lines=100000
scroll_on_output=0
scroll_on_keystroke=0
always_show_tabs=0
show_add_tab_btn=0
hide_menubar=1
win_title=%s
login_shell=0
overlay_scrollbar=1
limit_scrollback=0
```

Diff:
```
diff Default.before Default.after 
12c12
< scrollbar_pos=0
---
> scrollbar_pos=1
15c15
< scroll_on_keystroke=1
---
> scroll_on_keystroke=0
20a21,22
> overlay_scrollbar=1
> limit_scrollback=0
```

So essentially I cannot use the "No scrollbar" settings any more without breaking scrolling.
Bug?
Thanks!

**Comment by davama** [comment]
Installed from source the stable version and i was able to get my scrolling to work again with my previous config....

Remoeved my source pkg and reinstalled using `pacaur` and all is well in the world again (╯°□°)╯︵ ┻━┻   ....very odd.... ┬─┬ノ( º _ ºノ)

closing

**Comment by realh** [comment]
I can reproduce the lack of scrolling in my current version (equivalent to AUR roxterm-git) so I'm reopening this. Is your stable version 3.10.1-1 from AUR/roxterm?

**Comment by davama** [comment]
used stable from this git project
https://github.com/realh/roxterm/releases/tag/stable

**Comment by davama** [comment]
Thanks!

**Comment by davama** [comment]
@realh 
FYI
Updated to `roxterm-git 1:3.10.3-1` but still see the issue...

Had to change my Profile to make scrolling to work again:
```
scrollbar_pos=1
```
Thanks!

**Comment by realh** [comment]
Odd, same here. I thought it was working with no scrollbar yesterday, but I must have tested it wrong. It seems like GtkScrolledWindow ignores scroll events if the scrollbar is hidden.

**Comment by realh** [comment]
Hopefully this is fixed properly now, so that scrolling still works with the scrollbar invisible (scrollbar_pos=0).
