### ISSUE TITLE
Starting roxterm with a session doesn't work properly

### ISSUE THREAD

**Issue by kruthers64** [realh/roxterm#235]
I tried saving a simple session with one window with 2 tabs with different names and directories.  When I try to open a new window with that session I get inconsistent results.  The window geometry is ignored and the window is tiny, or sometimes as wide as the screen.  Most of the time one tab is missing.  Sometimes the window disappears instantly (maybe both tabs are missing?)  I'm trying it like this:
`roxterm --session=test01`

I can verify that setting window size should work because if I set it manually on the commandline without a session it works fine:
`roxterm --geometry=140x68+0+200`

Here's the session file (anonymized):
```
<roxterm_session id='test01'>
  <window geometry='140x68+0+200'
      title_template='%s' font='Inconsolata Medium 14'
      title_template_locked='1'
      title='username@hostname: ~/projects/company/proj1000/' role='(null)'
      shortcut_scheme='Default' show_menubar='0'
      always_show_tabs='1' tab_pos='2'
      show_add_tab_btn='1'
      disable_menu_shortcuts='0' disable_tab_shortcuts='0'
      maximised='0' fullscreen='0' borderless='0' zoom='1.000000'>
    <tab profile='Default'
        colour_scheme='default-custom' cwd='/home/username/projects/company/proj1000'
        title_template='Code' window_title='username@hostname: ~/projects/company/proj1000'
        title_template_locked='1' current='0'>
      <command argc='1'>
        <arg s='/bin/bash' />
      </command>
    </tab>
    <tab profile='Default'
        colour_scheme='default-custom' cwd='/home/username/projects/company/proj1000/cad'
        title_template='Cad' window_title='username@hostname: ~/projects/company/proj1000/cad'
        title_template_locked='1' current='1'>
      <command argc='1'>
        <arg s='/bin/bash' />
      </command>
    </tab>
  </window>
</roxterm_session>
```

I'm running the PPA version 3.10.1-1ppa1focal1 of roxterm on Linux Mint 20.1

Hope there's a simple fix.  Thanks!

**Comment by realh** [comment]
Does it make any difference if you remove the geometry attribute from the session file? What does it show on the console if you set G_MESSAGES_DEBUG=all? You'll probably have to add the --separate option or run it from a different terminal program.

**Comment by kruthers64** [comment]
I did try removing the geometry attr from the session before but the result is worse, the window is even smaller, something like 11x2 characters.  But the interesting thing is that it seems to fix the missing tabs problem; I tried it a dozen or so times and always got 2 tabs.

Setting that env var doesn't add much to the output, but here it is:
```
> roxterm --session=test01 
** (roxterm:7191): DEBUG: 09:11:13.776: Initializing XApp GtkModule
(roxterm:7191): GLib-GIO-DEBUG: 09:11:13.779: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
** (roxterm:7191): DEBUG: 09:11:13.779: Adding a Favorites shortcut to GtkPlacesSideBars

(roxterm:7191): Gtk-CRITICAL **: 09:11:13.841: gtk_window_set_default_size: assertion 'height >= -1' failed
```

And here it is again when the window randomly is super wide:
```
> roxterm --session=test01 
** (roxterm:7152): DEBUG: 09:11:11.000: Initializing XApp GtkModule
(roxterm:7152): GLib-GIO-DEBUG: 09:11:11.003: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
** (roxterm:7152): DEBUG: 09:11:11.003: Adding a Favorites shortcut to GtkPlacesSideBars

(roxterm:7152): Gdk-WARNING **: 09:11:11.075: Native Windows wider or taller than 32767 pixels are not supported
```

And last, here it is when the geom attr is NOT in the session file:
```
> roxterm --session=test01 
** (roxterm:8615): DEBUG: 09:49:46.943: Initializing XApp GtkModule
(roxterm:8615): GLib-GIO-DEBUG: 09:49:46.946: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
** (roxterm:8615): DEBUG: 09:49:46.946: Adding a Favorites shortcut to GtkPlacesSideBars

(roxterm:8615): VTE-CRITICAL **: 09:49:46.976: void vte_terminal_set_size(VteTerminal*, long int, long int): assertion 'columns >= 1' failed

(roxterm:8615): VTE-CRITICAL **: 09:49:46.977: void vte_terminal_set_size(VteTerminal*, long int, long int): assertion 'columns >= 1' failed
```

And one last thing - I temporarily removed my roxterm config and tried again.  The geometry problems are not changed at all, but the missing tabs problem goes away even though the geometry attr is present in the session file. More mysteries...

**Comment by realh** [comment]
Hopefully the latest git will fix these issues. Would you be able to test it before I release?

**Comment by kruthers64** [comment]
Yes, I just compiled it and it works!  No geometry problems or missing tabs.  For real use I'll stick with the PPA so I get future updates, assuming that's going to be updated soon.

Thanks, I love roxterm and really appreciate that you're maintaining it.

**Comment by realh** [comment]
Glad to hear it, thanks for the feedback.
