### ISSUE TITLE
roxterm segfault when closing tab

### ISSUE THREAD

**Issue by sopleb** [realh/roxterm#238]
OS: Debian 10
when i close a tab i get a segfault:
```
(roxterm:10842): GLib-GObject-WARNING **: 18:00:44.879: invalid uninstantiatable type '(null)' in cast to 'MultitabCloseButton'

zsh: segmentation fault  roxterm
```

**Comment by gijsbers** [comment]
Which version of roxterm are you using? 
You can see this in the Help -> About window. 
With 3.11.1.2 I can't reproduce this bug.
Maybe try this: `G_MESSAGES_DEBUG=all roxterm`

**Comment by sopleb** [comment]
was using 3.3.1.15, will try using 3.11.1

**Comment by sopleb** [comment]
can confirm 3.11.1 works fine.
