### ISSUE TITLE
Fixing the PPA

### ISSUE THREAD

**Issue by MihaiIsvoranu** [realh/roxterm#242]
Hi there, can we please get the PPA to work on Ubuntu 21.10? As someone who uses a tiling window manager as a daily drive, I haven't found a terminal emulator better than this one.

**Comment by realh** [comment]
The package for focal should work with newer Ubuntu releases, but you may have to add the PPA manually to /etc/sources/list.d/. Is that not working now?

**Comment by mihaiadrian212** [comment]
Not working here.
`E: The repository 'http://ppa.launchpad.net/h-realh/roxterm/ubuntu impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by mihaiadrian212** [comment]
Oh, okay. It is working, I had to manually edit the sources.list.d/ dir and replace 'impish' with 'focal'. Thanks a lot, realh!

**Comment by realh** [comment]
Thanks for the feedback. I might leave this issue open so that other people can find the solution more easily.

**Comment by vossenjp** [comment]
As of 2023-08-24, the PPA is now working for Lunar, Jammy, and Focal, see https://launchpad.net/~h-realh/+archive/ubuntu/roxterm/+packages.  See https://github.com/realh/roxterm/issues/249#issuecomment-1690533162 about Bionic.

**Comment by FenderDOOD** [comment]
PPA for noble seems to be signed with a weak key. PPA  works, but with warning:

```W: https://ppa.launchpadcontent.net/h-realh/roxterm/ubuntu/dists/jammy/InRelease: Signature by key CA76D653B56F3C0A67BAEC9CBA0835874C32D80B uses weak algorithm (rsa1024)```

**Comment by realh** [comment]
> PPA for noble (Ubuntu 24.04) seems to be signed with a weak key. PPA works, but with warning:

I think that's a separate issue, #200. Canonical still haven't resolved the problem AFAIK. Closing this one.
