### ISSUE TITLE
Enable wrap_switch_tab property

### ISSUE THREAD

**Issue by Thanos-Bl** [realh/roxterm#248]
Hi and thanks for maintaining roxterm.

I'm using roxterm-3.12.1 with gtk3-3.24.37 glib-2.74.6 vte-0.72.0 on a Linux From Scratch 11.3 system with plain icewm-3.3.2.
I would prefer when switching/moving tabs via the keyboard settings I've set, to cycle through tabs. To be clear, when I'm on the last tab and switch right, to go to the first tab, and from the first tab switching left to go to the last. I see that there is a wrap_switch_tab property that seems to do what I want. If that's so how can I enable it, and if not is there another way to accomplish what I want?

Thanks again
Thanos

**Comment by realh** [comment]
If you edit your profile and select the Tabs section the first toggle option under the "Tab title" field is labeled "Wrap when switching tabs". That should enable the wrapping you want.

**Comment by Thanos-Bl** [comment]
I'm so inattentive! Thanks for the quick response, and keep up the good work!
