### ISSUE TITLE
Color Scheme reverts to GTK after closing.

### ISSUE THREAD

**Issue by FenderDOOD** [realh/roxterm#252]
I prefer to set the Nocturne dark mode for color scheme. However after installing the 3.13.2 from the Jammy repository, I got the GTK light mode scheme.   So I set to Nocturne from the menu, and then even save session as 'Default'.  But when I exit, then start the term again it has resumed the GTK color scheme. 

OS: Linux Mint 21.2
Cinnamon Desktop

I'm happy to provide any other information you require. Thanks.

**Comment by realh** [comment]
If you set the colour scheme from the menu it only applies to the current session. You should be able to make a persistent setting, either by Edit Current Profile > Appearance, or opening the Configuration Manager and selecting one of the radios (do the latter twice, once while the desktop* is in light mode and once in dark mode). I hope that fixes it for you, let me know if it doesn't.

*That's for GNOME. I don't know whether other desktops use the same setting mechanism (GSettings/DConf). If not, roxterm will just ignore what the desktop's doing.

**Comment by FenderDOOD** [comment]
Thanks for that... that works.   I have implemented that.  In previous versions the Preference -> Select Color Scheme would persist, and I never noticed the other place to select scheme.   I guess I have been lucky so far. 

Thanks for the quick response.
