### ISSUE TITLE
FEATURE REQUEST: disable more/all keyboard shortcuts

### ISSUE THREAD

**Issue by ddan39** [realh/roxterm#255]
Just found this terminal emulator, and I have been mostly loving it. One thing that is a must have for me though, since I use a lot of TUI applications, is being able to disable all of the keyboard shortcuts. For example, when I try to use weechat in roxterm, if I have more than 1 tab open, roxterm steals alt+1, alt+2 etc for each tab opened, which would normally be used by weechat. The same is true of the Alt key in general for opening the menu, but I can at least hide the menu which shuts off that shortcut. That is not ideal though. I would actually like the menu there, but without stealing my Alt key. The F10 key is also used to open the File menu, which is often used by TUI's, like htop.

Please and Thanks!

**Comment by dampdigits** [comment]
Go to preferences (right click if menu is disabled) > Edit Current Profile > Keyboard
There you get the option to disable F10 and Alt keys.

![Screenshot_2023-12-11_17-55-56](https://github.com/realh/roxterm/assets/113439449/4d16f375-ae87-49b2-aba1-1c9d89612013)
