### ISSUE TITLE
[CATPPUCCIN] color theme for [NEOVIM] is unsupported in ROXTerm version 2.9.5

### ISSUE THREAD

**Issue by dampdigits** [realh/roxterm#256]
### Description
[Catccuppin](https://github.com/catppuccin) color theme for [Neovim](https://github.com/neovim) does not seems to work on ROXTERM. The same Neovim configuration works perfectly fine on other terminals like [Kitty](https://github.com/kovidgoyal/kitty), [URXVT](https://rxvt.sourceforge.net/) and [Alacritty](https://github.com/alacritty/alacritty). I have tried different TERM environment variables like `gnome-256color`, `xterm-256color` and `rxvt-unicode-256color` but nothing seems to work.

### Roxterm version
```
ROXTerm 2.9.5
GTK 2/VTE 9 build
```

### ROXTERM config
```
[roxterm profile]
font=NotoSansM Nerd Font 10
scrollback_lines=5000
always_show_tabs=0
height=30
scroll_on_keystroke=1
colour_scheme=
background_type=0
saturation=0.208861
scroll_background=1
background_img=/home/dampdigits/Pictures/wallpapers/debian003.jpg
show_add_tab_btn=0
maximise=0
hide_menubar=1
width=90
visible_bell=0
cursor_shape=0
cursor_blink_mode=1
use_custom_command=0
use_ssh=0
ssh_address=localhost
show_tab_num=1
title_string=%s
win_title=hack  /\\___<(  --   |   --   )>___/\\  mach
command=/usr/bin/env TERM=gnome-256color /bin/bash
term=gnome-256color
color_term=
```

### Neovim version
```
NVIM v0.10.0-dev-1809+g529498685
Build type: Release
LuaJIT 2.1.1700008891
```

### Expected behavior
![kittynvim](https://github.com/realh/roxterm/assets/113439449/5a4c7671-84b3-4087-9168-9085a730e3f5)

<hr>

### Actual behavior
![roxtermnvim](https://github.com/realh/roxterm/assets/113439449/f5ae4654-d5bd-4331-bfd4-2a9e0680cbf0)

<hr>

Either I have messed up the configurations and settings of ROXTERM in which case I'd appreciate some guidance or perhaps ROXTERM requires some additional settings to support Catppuccin color theme for nvim.

**P.S.**: I've got used to ROXTERM and really happen to like it though more modern alternatives are available, probably because of ROXTERM's simplicity, built-in features and good support for older machines (also seems to be quite lightweight imo). @realh I would really appreciate if you take a look at this.

**Comment by realh** [comment]
It might be because of the TERM value of "gnome-256color". The default is xterm-256color. Try deleting the TERM part of the command option in your profile, and the two lines after that (I think the `color_term` key is a relic from an old version, because there's currently no reference to it in the source code). If that doesn't fix it, please could you test with another vte-based terminal, for example gnome-terminal, and see if it has the same problem?

**Comment by realh** [comment]
I also noticed you're not using roxterm's overlay scrollbars option (available in the Scrolling section of the profile). It looks better and saves space, especially when the scrollbar is redundant while using vim.

**Comment by dampdigits** [comment]
The reason why I modified TERM value to `gnome-256color` from `xterm-256color` is because it cause some problems with nvim characters, as shown in the picture below. Changing it back to `xterm-256color` however didn't solve the theme color problem

![Screenshot_2023-12-11_22-26-33](https://github.com/realh/roxterm/assets/113439449/07ef8e08-7d21-47a1-9c8c-279a641f65c9)

### Modified config
```
[roxterm profile]
font=NotoSansM Nerd Font 10
scrollback_lines=5000
always_show_tabs=0
height=30
scroll_on_keystroke=1
colour_scheme=
background_type=0
saturation=0.208861
scroll_background=1
background_img=/home/dampdigits/Pictures/wallpapers/debian003.jpg
show_add_tab_btn=0
maximise=0
hide_menubar=1
width=90
visible_bell=0
cursor_shape=0
cursor_blink_mode=1
use_custom_command=0
use_ssh=0
ssh_address=localhost
show_tab_num=1
title_string=%s
win_title=hack  /\\___<(  --   |   --   )>___/\\  mach
command=/usr/bin/env
term=xterm-256color
```
<hr>

the below config didn't work either
```
command=/usr/bin/env TERM=gnome-256color /bin/bash
term=gnome-256color
color_term=
```

Proceeding to test with gnome-terminal.

**Comment by dampdigits** [comment]
> I also noticed you're not using roxterm's overlay scrollbars option (available in the Scrolling section of the profile). It looks better and saves space, especially when the scrollbar is redundant while using vim.

How do I do that? Which value should be changed?

**Comment by dampdigits** [comment]
> If that doesn't fix it, please could you test with another vte-based terminal, for example gnome-terminal, and see if it has the same problem?

To my surprise it works on gnome-terminal as well.

**Comment by realh** [comment]
Overlay scrollbars can be enabled by adding `overlay_scrollbar=1` to your profile file, or in the GUI (Preferences > Edit Current Profile):
![Screenshot from 2023-12-12 16-26-34](https://github.com/realh/roxterm/assets/8783151/357707a7-1271-4a2b-b8a9-de4c71ef5af3)

If that option is missing, you probably have an obsolete version of roxterm, which hopefully also explains the problem with catppuccin. I've installed the nvim theme myself and it works correctly in roxterm for me. Maybe full color isn't enabled in your version of roxterm? If it is, the `COLORTERM` environment variable should be set to `truecolor` by vte.

The latest version of roxterm is 3.14.3. You can get it from [my PPA](https://launchpad.net/~h-realh/+archive/ubuntu/roxterm) for Debian-based systems, or from `roxterm-git` in AUR for Arch-based systems.

**Comment by dampdigits** [comment]
You're right I'm using roxterm version **2.9.5 GTK 2/VTE 9 build** as I mentioned earlier, because apparently that's the latest version available via **apt** (I'm using a debian based OS).

I have tried changing the value of `COLORTERM` to `truecolor` and yet it didn't work. Also, the 'overlay_scrollbar' variable is missing. So, it's safe to conclude roxterm version **2.9.5 GTK 2/VTE 9 build** doesn't support **Catppuccin** colorscheme for **Neovim**.
Installing roxterm version 3.14.3 from [Roxterm PPA](https://launchpad.net/~h-realh/+archive/ubuntu/roxterm) and closing this issue.
