### ISSUE TITLE
Latest release 3.14 does not follow or update to current config.

### ISSUE THREAD

**Issue by W54J04S07T** [realh/roxterm#257]
On Arch it starts up with a white background and not the saved session configuration.
Change the config back to original layout and "save session" and next start config is lost.

Are we pointing to some other location for the config now?

**Comment by realh** [comment]
Session saving was really just repurposing some old code after X sessions were deprecated in GNOME etc. I never thoroughly tested it, and it looks like it's broken. You can use the Profile Editor and Configuration Manager to do most of what (should be) possible with saved sessions. Configuration Manager is where you can set the default profile and colour scheme.
