### ISSUE TITLE
Broken tab configuration in session saving

### ISSUE THREAD

**Issue by milisarge** [realh/roxterm#263]
I opened two tabs and save session but could not restore it, because of `tab cwd` saving. Here is the point:

```
<tab profile='Default'
        /tmpcwd=''
        title_template='milis' window_title='mak@dcerb:/tmp'
        title_template_locked='1' current='0'>
      <command argc='1'>
        <arg s='/bin/bash' />
      </command>
    </tab>
```

it should be `cwd='/tmp'` instead of  `/tmpcwd=''`

**Comment by milisarge** [comment]
exactly it occurs when i change the color scheme. it saves single quotes weirdly.

**Comment by milisarge** [comment]
it seems, color-scheme does not work if i am not missing, this configuration doesn't load related schemes.

```
<tab profile='Default'
        colour_scheme='default'
        cwd='/tmp'
        title_template='dasda' window_title='uzi@makina:/tmp'
        title_template_locked='1' current='0'>
      <command argc='1'>
        <arg s='/bin/bash' />
      </command>
    </tab>
    <tab profile='Default'
        colour_scheme='Nocturne'
        cwd='/tmp'
        title_template='%t. %s' window_title='uzi@makina:/tmp'
        title_template_locked='0' current='1'>
      <command argc='1'>
        <arg s='/bin/bash' />
      </command>
    </tab>
```

**Comment by realh** [comment]
I discovered the bug with cwd a while ago (see #257), but I forgot to make sure I was on the master branch when I fixed it. I've just rectified that; are you able to check it out from git and test it? I haven't seen the issue with single quotes/&apos; before, so if you can reproduce it please go into more detail.

**Comment by milisarge** [comment]
thanks much, I tested and it works. I have also no single quote problem.
