### ISSUE TITLE
Huge memory leak

### ISSUE THREAD

**Issue by realh** [realh/roxterm#99]
How to reproduce:
1. Close all roxterm windows.
2. In an xterm (shell=bash) type:

roxterm & sleep 5; ps l $(pgrep roxterm); for ((x=0;x<50;x++)); do roxterm -e true; done; sleep 10; ps l $(pgrep roxterm)

Output:

    [2] 6682

    ** (roxterm:6682): WARNING **: Failed to connect to session manager: SESSION_MANAGER environment variable not defined
    [1]   Done                    roxterm
    F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
    0  1000  6682  6461   1   0 318404 13096 -      Sl   pts/4      0:00 roxterm
    F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
    0  1000  6682  6461   1   0 345452 37696 -      Sl   pts/4      0:02 roxterm

What should happen:
The second RSS shouldn't be much larger than the first RSS.

What actually happens:
The second RSS (37696) is much larger than the first RSS (13096).

Kind regards,
nignag

Reported by: *anonymous

Original Ticket: [roxterm/bugs/98](https://sourceforge.net/p/roxterm/bugs/98)

**Comment by gituser** [comment]
Hi @realh !

Did you fix this issue in the end ? If so in which release? I can't seem to find specific commit for this issue.

I've been using roxterm 2.8.1 for quite some time and this issue annoys me from time to time, I can't really upgrade to the latest one as it has different tabs styling and not usable for me. 

Would be nice to backport this fix for 2.8.1 if possible.

Thanks.

**Comment by realh** [comment]
It does seem to have improved since you reported it; the RSS figures are now 40176 and 42904. It looks like I fixed some potential leaks with (some of) the commits I made on 2013-Nov-07, but that predates version 2.8.1.

**Comment by gituser** [comment]
I'm trying now self-built revision eaf5c0662930dd016623fe659d65a224b03bd7c7 without commit d9ab64cc7b35fc406726eaa5c334d6063b6be0c6 (tab highlighting) roxterm-gtk2 will see how it goes.

Thanks!
